name       : polari
version    : 3.34.1
release    : 18
source     :
    - https://download.gnome.org/sources/polari/3.34/polari-3.34.1.tar.xz : bcf420c2a2a8c6ca39e95ffebb71c51fbf0f1866255e068ff6d78d63569c8e71
license    : GPL-2.0
component  : network.irc
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-logger-0.2)
    - itstool
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
