name       : polari
version    : 3.36.1
release    : 20
source     :
    - https://download.gnome.org/sources/polari/3.36/polari-3.36.1.tar.xz : c4c2aaa66b202eec3ab7dbfe08b8bb730e40cafc77cb0a9eae190bf1c8c1b5e6
license    : GPL-2.0-or-later
component  : network.irc
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-logger-0.2)
    - itstool
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
