name       : polari
version    : 3.20.3
release    : 4
source     :
    - https://download.gnome.org/sources/polari/3.20/polari-3.20.3.tar.xz : 9085ad756060eb9759471c195cfe6af22b99489b8f28dc05ff4c91ccaf37c2f0
license    : GPL-2.0
component  : network.im
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(telepathy-glib)
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
