name       : polari
version    : 3.28.1
release    : 14
source     :
    - https://download.gnome.org/sources/polari/3.28/polari-3.28.1.tar.xz : cc271aa1e8ba858caa6d29e2e46dd9f837b4dfd9ec8d9737ececcebc6890c680
license    : GPL-2.0
component  : network.irc
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-logger-0.2)
    - itstool
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
