name       : polari
version    : 3.20.2
release    : 3
source     :
    - https://download.gnome.org/sources/polari/3.20/polari-3.20.2.tar.xz : 4b7641e54ee8a2e6018e1b4cea4802d94d90c2f09b9558e0a767838effd1347f
license    : GPL-2.0
component  : network.im
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(telepathy-glib)
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
