name       : polari
version    : 3.18.1
release    : 2
source     :
    - https://download.gnome.org/sources/polari/3.18/polari-3.18.1.tar.xz : 554a089b1edf88d49408ecf6ce79ad6f7114ecf557753c8f39a9af153a76843a
license    : GPL-2.0
component  : network.im
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(telepathy-glib)
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
