name       : polari
version    : 3.34.0
release    : 17
source     :
    - https://download.gnome.org/sources/polari/3.34/polari-3.34.0.tar.xz : daca0c060c9f29c246aa6300e645ae9cee36bb1b80018e042ca572273af5e225
license    : GPL-2.0
component  : network.irc
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-logger-0.2)
    - itstool
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
