name       : polari
version    : 3.36.2
release    : 21
source     :
    - https://download.gnome.org/sources/polari/3.36/polari-3.36.2.tar.xz : acfcdb1653bf2e47bd5ab891e38a0002c2f93c160397119c3a0b5c3ec57d208a
license    : GPL-2.0-or-later
component  : network.irc
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-logger-0.2)
    - itstool
rundeps    :
    - gjs
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
