name       : polari
version    : '43.0'
release    : 31
source     :
    - https://gitlab.gnome.org/GNOME/polari/-/archive/43.0/polari-43.0.tar.gz : 1afe7e1481f835713b5da62c39d04089f9d90404282b8e1babe7c301b4fb2e93
license    : GPL-2.0-or-later
homepage   : https://wiki.gnome.org/Apps/Polari
component  : network.irc
summary    : Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
description: |
    Polari is an IRC client which enables you to chat with people around world through large chatrooms or via private messaging.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk4)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-logger-0.2)
    - desktop-file-utils
    - itstool
rundeps    :
    - gjs
    - libadwaita
    - libgtk-4
    - telepathy-idle
    - telepathy-logger
    - telepathy-mission-control
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
